//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiD.Idefix.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IdefixResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdefixResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiD.Idefix.Resources.IdefixResources", typeof(IdefixResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                   .:HMMMMHn:.  ..:n..
        ///                                .H*&quot;``     `&quot;%HM&quot;&quot;&quot;&quot;&quot;!x.
        ///         :x                    x*`           .(MH:    `#h.
        ///        x.`M                   M&gt;        :nMMMMMMMh.     `n.
        ///         *kXk..                XL  nnx:.XMMMMMMMMMMML   .. 4X.
        ///          )MMMMMx              &apos;M   `^?M*MMMMMMMMMMMM:HMMMHHMM.
        ///          MMMMMMMX              ?k    &apos;X ..&quot;*MMMMMMM.#MMMMMMMMMx
        ///         XMMMMMMMX               4:    M:MhHxxHHHx`MMx`MMMMMMMMM&gt;
        ///         XM!`   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Idefix {
            get {
                return ResourceManager.GetString("Idefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         :x                     x*`           .(MH:    `#h.
        ///       x.`M                    M&gt;        :nMMMMMMMh.     `n.
        ///        *kXk..                 XL  nnx:.XMMMMMMMMMMML   .. 4X.
        ///         )MMMMMx               &apos;M   `^?M*MMMMMMMMMMMM:HMMMHHMM.
        ///         MMMMMMMX               ?k    &apos;X ..&quot;*MMMMMMM.#MMMMMMMMMx
        ///        XMMMMMMMX                4:    M:MhHxxHHHx`MMx`MMMMMMMMM&gt;
        ///        4M      M                 `x   4MM&quot;`&quot;&quot;``HHhMMX  &quot;MMMMMMMM.
        /// </summary>
        internal static string IdefixTailLeft {
            get {
                return ResourceManager.GetString("IdefixTailLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          :x                    x*`           .(MH:    `#h.
        ///        x.`M                   M&gt;        :nMMMMMMMh.     `n.
        ///         *kXk..                XL  nnx:.XMMMMMMMMMMML   .. 4X.
        ///          )MMMMMx              &apos;M   `^?M*MMMMMMMMMMMM:HMMMHHMM.
        ///          MMMMMMMX              ?k    &apos;X ..&quot;*MMMMMMM.#MMMMMMMMMx
        ///         XMMMMMMMX               4:    M:MhHxxHHHx`MMx`MMMMMMMMM&gt;
        ///         XM!`   ?M                `x   4MM&quot;`&quot;&quot;``HHhMMX  &quot;MMMMMMMM.
        /// </summary>
        internal static string IdefixTailRight {
            get {
                return ResourceManager.GetString("IdefixTailRight", resourceCulture);
            }
        }
    }
}
