name: Build feature branch

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SOLUTION_FILE: ./src/DiD.Idefix.sln
      PROJECT_FILE: ./src/DiD.Idefix/DiD.Idefix.csproj

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}
    - name: Build
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore
    - name: Get latest tag
      id: get-latesttag
      uses: WyriHaximus/github-action-get-previous-tag@v1
    - name: Get PackageVersion of csproj
      id: get-packageversion
      uses: naminodarie/get-net-sdk-project-versions-action@v1
      with:
        proj-path: ${{ env.PROJECT_FILE }}
    - name: Fail not updated version
      if: ${{ steps.get-latesttag.outputs.tag }} == ${{ steps.get-packageversion.outputs.package-version }}
      run: |
        echo "PackageVersion in csproj matches latest git tag version. Please update PackageVersion."
        exit 1