name: Build feature branch

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SOLUTION_FILE: ./src/DiD.Idefix.sln
      PROJECT_FILE: ./src/DiD.Idefix/DiD.Idefix.csproj
      LATEST_VERSION: 0

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}
    - name: Build
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore
    - name: Get latest tag version
      run: ${{ env.LATEST_VERSION }} = git describe --tags --abbrev=0
    - name: Get PackageVersion of csproj
      uses: naminodarie/get-net-sdk-project-versions-action@v1
      id: get-packageversion
      with:
        proj-path: ${{ env.PROJECT_FILE }}
    - name: Fail not updated version
      if: ${{ env.LATEST_VERSION }} == ${{ steps.get-packageversion.outputs.package-version }}
      run: |
        echo "PackageVersion in csproj matches latest git tag version. Please update PackageVersion."
        exit 1