name: Publish to nuget.org

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SOLUTION_FILE: ./src/DiD.Idefix.sln
      PROJECT_FILE: ./src/DiD.Idefix/DiD.Idefix.csproj

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}
    - name: Build
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore
    - name: Publish to nuget.org
      id: publish-nuget-org
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: ${{ env.PROJECT_FILE }}
        VERSION_REGEX: '^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$'
        TAG_FORMAT: '*'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish to github packages
      run: dotnet nuget push "${{ steps.publish-nuget-org.outputs.PACKAGE_PATH }}" --api-key "${{ secrets.GH_PACKAGES_TOKEN }}" --source "https://nuget.pkg.github.com/dev-in-disguise/index.json" 
